# Generated by Django 4.2.29 on 2026-03-29 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barter', '0002_add_match_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='search_radius_miles',
            field=models.PositiveSmallIntegerField(default=25, help_text='Max distance (mi) for local matching, 1–50.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
